services:
  api:
    build: .
    container_name: fastapi-adlc
    environment:
      TESSDATA_PREFIX: "/tessdata"
      PORT: 8087
    ports:
      - '8087:8087'
    restart: "no"
    networks:
      - adlc
    healthcheck:
      test: curl --fail http://api:8087/docs || exit 1
      interval: 10s
      timeout: 10s
      retries: 4
      start_period: 10s
      start_interval: 5s
  test:
    build: ./test
    container_name: test-adlc
    depends_on:
      api:
        condition: service_healthy
    restart: "no"
    networks:
      - adlc

networks:
  adlc: {}
