services:
  api:
    build: .
    container_name: fastapi-adlc
    environment:
      TESSDATA_PREFIX: "/tessdata"
      PORT: 8087
    ports:
      - '8087:8087'
    restart: "no"
    networks:
      - adlc
  test:
    build: ./test
    container_name: test-adlc
    depends_on:
      api:
        condition: service_started
    restart: "on-failure:3"
    networks:
      - adlc

networks:
  adlc: {}
